# Generated by Django 5.0.3 on 2024-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_list',
            field=models.ManyToManyField(related_name='teacher_list', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='diploma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='interests',
            field=models.ManyToManyField(related_name='interests_teacher', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interests_student', to='accounts.subject'),
        ),
    ]
