# Generated by Django 5.0.3 on 2024-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher_list_teacher_diploma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='interests',
        ),
        migrations.AddField(
            model_name='teacher',
            name='price_list',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
