# Generated by Django 5.0.3 on 2024-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_favorite_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name=models.ImageField(default='profile_images/default.jpg', upload_to='images/')),
        ),
    ]
