# Generated by Django 5.0.3 on 2024-05-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_teacher_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
